### ISSUE TITLE
Error with background shorthand property

### ISSUE THREAD

**Issue by urbananimal** [marceloverdijk/lesscss-java#14]
If the CSS background shorthand property is used and includes position and size values lesscss-java throws a ClassCastException:

for example -      `background: url(@url_var) top / cover no-repeat;`

output shows: 
`java.lang.ClassCastException: org.mozilla.javascript.ConsString cannot be cast to java.lang.String
    at org.lesscss.LessCompiler.compile(LessCompiler.java:251)`

**Comment by mgarmash** [comment]
Caused by: java.lang.ClassCastException: org.mozilla.javascript.ConsString cannot be cast to java.lang.String
at org.lesscss.LessCompiler.compile(LessCompiler.java:251)
at org.lesscss.LessCompiler.compile(LessCompiler.java:302)

``` css

// exception
.test {
    filter: alpha(opacity = 100);
}

// fixed version
.test {
    filter: alpha(opacity=100);
}
```
